export const features=[
    { icon:"uil uil-book-reader",name:"global learning enviroment" ,para:"Help our students expand their worldview by exploring perceptions and connections to the community we are building. Students benefit from a global presence, highly qualified tutors, develop diverse skills and understand their own lives."},
    { icon:"uil uil-user-arrows",name:"individual and private batches",para:"We offer the best approach by providing diverse learning experiences to help students learn quickly and efficiently. We have an individual and batch system."},
    { icon:"uil uil-channel",name:"Personalized course structure (Structure tailored Lesson)" ,para:"We have designed the courses according to the needs of the students and meet  the real needs of Islamic education. Our courses are tailored to each individual to  help students learn more effectively at their language level."},
    { icon:"uil uil-desktop-alt",name:"online panel" ,para:"Online panels can also provide students with the opportunity to ask questions, get feedback and hear about the latest developments in their field of study from experts in the field. Online panels can be a valuable resource for students who are studying remotely or online, giving them access to the same level of expert insight and guidance as on-campus students. "},
    { icon:"uil uil-arrow-growth",name:"learn online effectively",para:"Our teaching methods are designed for effective learning. The characteristics of    effective learning describe the behavior with which children learn. To learn well,    students should adopt method possibilities with curiosity, energy, and    enthusiasm. We are constantly developing teaching and learning methods. The    biggest benefit of learning Islamic classes online is that you can connect with    your teacher from anywhere in the world. Our platform supports mobile phones    and computers."},
    { icon:"uil uil-graduation-cap",name:"Multilingual & verified Tutors" ,para:"Each tutor goes through a verification process conducted by our experts. We have focused on recruiting the best tutors from around the world. Tutoring services for multilingual students. The ESL program offers a unique teacher-tutor intervention that combines classroom and mentoring."},
    { icon:"uil uil-globe",name:"Worldwide recognized ",para:"Our platform is recognized worldwide and we have a global footprint spanning the US, UK, Europe, Malaysia, Indonesia, Kuwait, Qatar and Dubai."},
    { icon:"uil uil-clock-seven",name:"24/7 Services", para:"This can be especially beneficial for students who have busy schedules or live in different time zones. It helps students track their learning progress and overcome any obstacles they may encounter, resulting in more effective and stress-free online learning. This removes potential obstacles to success that students might encounter with learning."},
    { icon:"uil uil-file-check-alt",name:"Self-assessment tests & Certificates", para:"Students can assess their own progress and understanding with the help of self-assessment tests at the end of each unit.. They can also identify areas of their study that they need to focus on."},
]